# Generated by Django 3.2.13 on 2022-06-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(null=True)),
                ('match_details', models.CharField(max_length=200, null=True)),
                ('venue', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away')], max_length=5, unique=True)),
            ],
            options={
                'ordering': ('match_date',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('irish_name', models.CharField(default='to be confirmed', max_length=200, null=True)),
                ('date_of_birth', models.DateField(null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Team_Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.IntegerField(null=True, unique=True)),
                ('game_status', models.CharField(choices=[('Starting', 'Starting'), ('Sub', 'Sub')], max_length=10)),
                ('goals', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('notes', models.CharField(max_length=50)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.match')),
                ('player', models.ManyToManyField(to='tracker.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200, null=True)),
                ('session_date', models.DateField(null=True)),
                ('player', models.ManyToManyField(to='tracker.Player')),
            ],
            options={
                'ordering': ('session_date',),
            },
        ),
    ]
