# Generated by Django 3.2.13 on 2022-06-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(choices=[('Home', 'Home'), ('Away', 'Away')], max_length=5),
        ),
    ]
