# Generated by Django 3.2.13 on 2022-06-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_match_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_selection',
            name='jersey_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team_selection',
            name='notes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team_selection',
            name='player',
            field=models.ManyToManyField(null=True, to='tracker.Player'),
        ),
    ]
